### ISSUE TITLE
List of problems and considerations arising from projects porting

### ISSUE THREAD

**Issue by mdantonio** [rapydo/issues#29]
Note: this list is not prioritized

- [ ] #28 Dynamic server-name for nginx configuration
- [ ] #8 We have to create a common admin endpoint to manage users (but before that, we have to solve the user creation when user model has been extended
- [ ] #14 Subnet problem (since the db_net has fixed IP, we have to remove the network before to stard another rapydo stack)
- [ ] #27 Execution of custom command on the host (not on a container) 
- [ ] bower libs should be project-dependent. If I create bower libs for project A and then start project B i should re-create libs... but nothing inform that the current libs are produced for a different project
- [ ] Frontend has a terrible jungle of mounted folders ( to be simplified if this frontend will remaing for long time... ignore this point if the nodejs frontend will come quickly [few months])
- [ ] Frontend in production mode says "DEBUG is active"
- [ ] Utilities and backend mounted in debug.yaml: i feel the requirement to discuss a final decision about this (i don't like the internal (in container) python path explicitly configured externally (i.e. in compose)
- [x] On backend `rapydo` do not work, I have to execute `python template/__main__.py`
- [x] backend prints a warning for a missing import: template.apis.common called from the ouath2 module
- [x] PYTHONPATH=/code put in debug.yaml to make the backend work. This workaround is not required in production mode
- [x] #8 The last deployments have required to manually execute the initialize command, it didn't start automatically
- [x] I can define more projects (i.e. blueprints) on the same folder... but If i change project we have to  re-create the .env ... but nothing inform that the current .env file is produced by a different project

- [x] projects/template/backend/conf is mounted by compose and git detect is as an untracked file
- [x] rapydo-controller verifies the input parameters (e.g. required parameters, as --services with shell) only after a long list of checks... It is quite ugly to see and really poor efficient
- [x] we really need rapydo control start/remove/etc? We cannot simply do rapydo start/remove/etc?
- [x] The old "do restart" acted as remove + start. We actual restart is a compose restart (restart of services, not container) and start is like the old graceful. If I want to force the restart of all container what I have to do? `rapydo remove + rapydo start`? Or it is possibile to use a single command like before?
- [x] With not-check commands it's ok to perform some basic checks... but is quite ugly to print the long list of (CHECKED) messages... we should hide checked message when a check is not explicitly requested (and only print in case of warnings/errors)

**Comment by pdonorio** [comment]
wow :O that's some LOOONG list :O

**Comment by mdantonio** [comment]
>  rapydo-controller verifies the input parameters (e.g. required parameters, as --services with shell) only after a long list of checks... It is quite ugly to see and really poor efficient

Added to shell and interfaces a positional argument service, this solves the problem

**Comment by mdantonio** [comment]
> The old "do restart" acted as remove + start.

Removed for now, to be managed in the next version of rapydo (based on invoke?) as multiple command

**Comment by mdantonio** [comment]
> we really need rapydo control start/remove/etc? We cannot simply do rapydo start/remove/etc?

Remove control subcommands

Now we have directly

```
rapydo start
rapydo restart
rapydo remove
rapydo stop
rapydo toggle_freeze

```

**Comment by mdantonio** [comment]
> projects/template/backend/conf is mounted by compose and git detect is as an untracked file

Fixed with the commit above

**Comment by pdonorio** [comment]
Implemented some fixes. We have to wait for the next release to have them all.

**Comment by mdantonio** [comment]
With the new release the "PYTHONPATH" in debug can be removed?

**Comment by pdonorio** [comment]
> With the new release the "PYTHONPATH" in debug can be removed?

yep, it's in the backend build now: 
https://github.com/rapydo/build-templates/blob/master/backend/docker-entrypoint.sh#L81

**Comment by mdantonio** [comment]
> #8 We have to create a common admin endpoint to manage users (but before that, we have to solve the user creation when user model has been extended

Created a dedicated issue ( rapydo/issues#48 )


>  Utilities and backend mounted in debug.yaml: i feel the requirement to discuss a final decision about this (i don't like the internal (in container) python path explicitly configured externally (i.e. in compose)

In discussion in rapydo/issues#33

**Comment by mdantonio** [comment]
Created a dedicated issue ( rapydo/issues#49 ) for the remaing points related to the frontend

Since all points are resolved o linked to a dedicated issue, we can close here

**Comment by pdonorio** [comment]
For the sake of my poor mind please remove the open tasks here in the first post 🥇

**Comment by mdantonio** [comment]
> bower libs should be project-dependent. If I create bower libs for project A and then start project B i should re-create libs... but nothing inform that the current libs are produced for a different project

Done

**Comment by mdantonio** [comment]
> Frontend in production mode says "DEBUG is active"

Fixed. The variable API_DEBUG was missing, so the frontend started with Flask instead of GEvent
